### PR TITLE
add environment variables and command line options for specifying custom server, port and api key

### PR DESCRIPTION
**Pull request by gangelop**
I've never written javascript before so any feedback is very welcome.

I just really want to get this functionality as we use an internal instance of the Up1 server at work.

This pull request partially addresses issues #1 and #2 but some more work will be needed.

### CODE REVIEW

**Comment by gangelop** [comment]
Added command line arguments as well as environment variables. This should now completely resolve #1.

**Comment by gangelop** [comment]
@k3d3 Hello o/ This is ready to go from my side. Any comments appreciated.

**Comment by gangelop** [comment]
Double checking something about error handling...

**Comment by k3d3** [comment]
Looks good! Thanks for the contribution!

**Pull request merged**
